server:
  port: 8085

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ashokthombre/microservice-configuration
          clone-on-start: true
