server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka

spring:
  cloud:
    gateway:
      mvc:
        routes:
        # Route for user-service
        - id: USERSERVICE
          uri: lb://USERSERVICE  # Backend service URL for user-service
          predicates:
            - Path=/users/**           # Matches any path under /users/*
          filters:
            - AddRequestHeader=Custom-Header,CustomValue
        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE  # Backend service URL for user-service
          predicates:
            - Path=/hotels/**           # Matches any path under /users/*

        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE  # Backend service URL for user-service
          predicates:
            - Path=/ratings/**           # Matches any path under /users/*
          filters:
            - AddRequestHeader=Custom-Header,CustomValue