server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka

spring:
  cloud:
    gateway:
      #mvc:
        routes:
        # Route for user-service
        - id: USERSERVICE
          uri: lb://USERSERVICE  # Backend service URL for user-service
          predicates:
            - Path=/users/**           # Matches any path under /users/*
          filters:
            - AddRequestHeader=Custom-Header,CustomValue
        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE  # Backend service URL for user-service
          predicates:
            - Path=/hotels/**           # Matches any path under /users/*

        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE  # Backend service URL for user-service
          predicates:
            - Path=/ratings/**           # Matches any path under /users/*
          filters:
            - AddRequestHeader=Custom-Header,CustomVa

#okta configuration for api gateway
okta:
  oauth2:
    issuer: https://dev-68535878.okta.com/oauth2/default
    audience: api://default
    client-id: 0oajqyt7db7OPjzFU5d7
    client-secret: 0tU0SO8LBvP8cmCyq5py4LkXMWH5RAfRZhbfqAQPZlIjnpK_YZcQnUMLvrfplxTS
    scopes:
      - openid
      - profile
      - email
      - offline_access